<?php

/*	
	Generated by P.O.R.K. Generator v1.0

	@dbSchema@
*/

class @name@ extends dbObject
{
		function __construct($ID=false)
		{
			$this->__setupDatabase('@table@', // db table
				array('@primaryKey@' => 'ID',	// db field => object property
						@fields@),
						'@primaryKey@',	// primary db key 
						$ID);	// primary key value
			@relations@
			@foreignRelations@
			@multiRelations@
		}

@displayeditor@

@displayshort@
		
@display@	

}




?>